### ISSUE TITLE
GitLab Authentication Feature Status

### ISSUE THREAD

**Issue by Parsonswy** [yuvipanda/kubessh#32]
Hello.
I am interested in deploying kubessh in our Kubernetes cluster. We use GitLab and are interested in using GitLab for public key authentication. I see there is an [authentication implementation](https://github.com/yuvipanda/kubessh/blob/master/kubessh/authentication/gitlab.py) for GitLab, but it doesn't seem to match the current API spec for [retrieving user keys by username](https://docs.gitlab.com/ee/api/users.html#list-ssh-keys-for-user).

Is the implementation known to work using a different API route, or a WIP feature? We'd be interested in opening a PR if it's WIP to meet the spec if that is ok.

Thanks!

**Comment by yuvipanda** [comment]
Hello! Thank you for your interest :) I'm currently focusing on [jupyterhub-ssh](https://github.com/yuvipanda/jupyterhub-ssh) instead, so I've marked this project as inactive. You're welcome to fork and work on this if you wanna, but I'd recommend checking out jupyterhub-ssh for the most common use case I was using it for :)
